<li>
                            <div class="pic"><img src="[field:picname/]" width="100%" height="100%"></div>
                            <div class="con">
                                <div class="title">
                                    <a href="[field:arcurl/]"><h1>[field:title/]</h1></a>
                                    <div class="date">[field:pubdate function="GetDateTimeMK(@me)" /]</div>
                                    <div style="clear:both;"></div>
                                </div>
                                <p>[field:description /]</p>
                                <a href="http://xcp.huashifengxing.com/a/xinwenzhongxin/" class="more button button--moema button--inverted button--text-thick button--size-s">MORE</a>
                            </div>
                        </li>