<?php
$z[0]=Array("field","",75,104);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",129,152);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("sql","[field:content function='cn_substr(html2text(@me),200)'/] ",207,336);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("field","",363,386);
$z[3][4]=array();
$z[3][4]['name']="id";

?>