
                        <li class="p5">
                            <a href="[field:typelink/]">
                                <u class="cl"></u>
                                <u class="cr"></u>
                                <i></i>
                                <strong>[field:typename/]</strong>
                                <p>{dede:field.description function='html2text(@me)'/}<br />彰显品牌形象</p>
                            </a>
                        </li>
                    