<?php
$z[0]=Array("arcurl","",103,118);
$z[0][4]=array();
$z[1]=Array("litpic","",130,145);
$z[1][4]=array();
$z[2]=Array("arcurl","",255,270);
$z[2][4]=array();
$z[3]=Array("title","",293,307);
$z[3][4]=array();
$z[4]=Array("pubdate","",374,426);
$z[4][4]=array();
$z[4][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[5]=Array("description","",478,528);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,250)";

?>