                                    
                <li class="cur button button--wayra button--border-thick button--text-upper button--size-s"><a style="font-size:16px;" href="{dede:global.cfg_basehost/}"><div class="bai">首    页</div><div class="hong">home</div></a></li>
                <li class=" button button--wayra button--border-thick button--text-upper button--size-s"><a style="font-size:16px;" href="[field:typelink/]"><div class="bai">[field:typename/]</div><div class="hong">profile</div></a></li>
            