<!--  <li>
          <div class="pic"><a href="view.php?aid=[field:id/]"><img src="[field:picname/]"></a></div>
          <div class="title"><a href="view.php?aid=[field:id/]">[field:title/]</a></div>
        </li> -->
         <li>
          <div class="pic"><a href="view.php?aid=[field:id/]"><img src="/skin/images/yewu1.jpg"></a></div>
          <div class="title"><a href="view.php?aid=[field:id/]">宣传片制作</a></div>
        </li>
         <li>
          <div class="pic"><a href="view.php?aid=[field:id/]"><img src="/skin/images/yewu2.jpg"></a></div>
          <div class="title"><a href="view.php?aid=[field:id/]">课件制作</a></div>
        </li>
         <li>
          <div class="pic"><a href="view.php?aid=[field:id/]"><img src="/skin/images/yewu3.jpg"></a></div>
          <div class="title"><a href="view.php?aid=[field:id/]">微电影拍摄</a></div>
        </li>