<li><a href="[field:arcurl/]">
                	<div class="pic"><img src="[field:picname/]" width="100%" height="100%"></div>
                    <div class="title">
                        <h3>[field:title/]</h3>
                        <p>{dede:field.content/}</p>
                    </div>
                    <div class="date">[field:pubdate function="MyDate('Y-m-d',@me)"/]</div>
                </a></li>