<?php
$z[0]=Array("field","",68,97);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",133,156);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("arclist","    \r\n        <li>\r\n          <div class=\"pic\"><a href=\"view.php?aid=[field:id/]\"><img src=\"[field:picname/]\"></a></div>\r\n          <div class=\"title\"><a href=\"view.php?aid=[field:id/]\">[field:title/]</a></div>\r\n        </li>\r\n      ",253,554);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['orderby']="pubdate";
$z[2][4]['row']="3";

?>