<a style="width:150px;" href="{dede:field name='typeurl'}" class=" button button--ujarak button--border-medium button--round-s button--text-thick anlia">{dede:field name='typename'}</a>
                
        <div class="clear"></div>
    </div>
    
    <div class="play_items content01">
        <ul>
                <li>
                <a href="case_infr.php?cid=56&id=335#wcrd_infr">
                <div class="pic"><img src="/skin/1482311049.jpg" width="100%" height="100%"></div>
                <span class="intro">
                    <h5>童装</h5>
                    <p></p>
                </span>
                <div class="play1"></div>
                <div class="mask"></div>
                </a>
                </li>
                
                <div class="clear"></div>
        </ul>
    </div>
</div>
<!--案例作品-->

<!--合作客户-->
<div class="wrapper hzkh_bj" id="case2">
	<div class="outter">
    	<div class="clzp_con clzp_con1">
            <h1><font>合作</font>客户</h1>
            <h3>Company customers</h3>
        </div>
        <div class="content01 hzkh_items">
        	<ul>
                        	<li>
                	<div class="pic"><img src="/skin/images/1479280535.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479281063.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479283541.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479285963.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479282806.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479284647.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479287138.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479287972.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479282007.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479279531.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479281056.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479289195.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479286690.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479279460.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479285664.jpg"></div>
                </li>
                             	<li>
                	<div class="pic"><img src="/skin/images/1479285372.jpg"></div>
                </li>
                                 
                <div class="clear"></div>
            </ul>
        </div>
    </div>
</div>
<!--合作客户-->

<!--子页内容-->

<!--尾部footer-->
{dede:include filename="footer.htm"