<div class="case_items1 anlia case_items2">
        	    <a style="width:150px;" href="[dede:field name='typeurl'/]" class=" button button--ujarak button--border-medium button--round-s button--text-thick anlia">[dede:field name='typename'/]</a>
            
                
        <div class="clear"></div>
    </div>
    {dede:arclist    row='10'                 }
    <div class="play_items content01">
    	<ul>
            
                <li>
                <a href="[field:arcurl/]">
            	<div class="pic"><img src="[field:picname/]" width="100%" height="100%"></div>
                <span class="intro">
                	<h5>[field:title/]</h5>
                    <p></p>
                </span>
                <div class="play1"></div>
                <div class="mask"></div>
                </a>
                </li>
                  	
                        <div class="clear"></div>
        </ul>
    </div>
    {/dede:arclist}