<?php
$z[0]=Array("arclist","\r\n    <div class=\"play_items content01\">\r\n    	<ul>\r\n            \r\n                <li>\r\n                <a href=\"[field:arcurl/]\">\r\n            	<div class=\"pic\"><img src=\"[field:picname/]\" width=\"100%\" height=\"100%\"></div>\r\n                <span class=\"intro\">\r\n                	<h5>[field:title/]</h5>\r\n                    <p></p>\r\n                </span>\r\n                <div class=\"play1\"></div>\r\n                <div class=\"mask\"></div>\r\n                </a>\r\n                </li>\r\n                  	\r\n                        <div class=\"clear\"></div>\r\n        </ul>\r\n    </div>\r\n    ",330,981);
$z[0][4]=array();
$z[0][4]['row']="10";

?>