<li>
                <a href="[field:arcurl/]">
                <div class="pic"><img src="[field:picname/]" width="100%" height="100%"></div>
                <span class="intro">
                    <h5>[field:title/]</h5>
                    <p></p>
                </span>
                <div class="play1"></div>
                <div class="mask"></div>
                </a>
                </li>