<?php
$z[0]=Array("global","",58,80);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("channelartlist","\r\n        <li><a href=\"/m/list.php?tid={dede:field name='id'/}\">{dede:field name='typename'/}</a></li>\r\n        ",218,386);
$z[1][4]=array();
$z[1][4]['typeid']="top";
$z[2]=Array("arclist","    \r\n        <li><a href=\"\"><img src=\"[field:picname/]\" style=\"width:100%;\" /></a></li>\r\n      ",481,657);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['orderby']="pubdate";
$z[2][4]['row']="3";
$z[2][4]['typeid']="20";

?>