<?php
$z[0]=Array("field","",137,156);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",157,183);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",226,253);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",293,344);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1190,1217);
$z[4][4]=array();
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("channel","\r\n                <li class=\" button button--wayra button--border-thick button--text-upper button--size-s\"><a style=\"font-size:14px;color:#000;\" href=\"[field:typelink/]\"><div class=\"bai\">[field:typename/]</div><div class=\"hong\">[field:typename/]</div></a>\r\n                </li>\r\n            ",1305,1654);
$z[5][4]=array();
$z[5][4]['row']="8";
$z[5][4]['type']="top";
$z[6]=Array("field","",4363,4414);
$z[6][4]=array();
$z[6][4]['name']="description";
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("field","",4701,4724);
$z[7][4]=array();
$z[7][4]['name']="seotitle";
$z[8]=Array("channel","\r\n        	<a href=\"[field:typelink/]\" class=\"button button--ujarak button--border-medium button--round-s button--text-thick\">[field:typename/]</a>\r\n        ",4834,5065);
$z[8][4]=array();
$z[8][4]['row']="10";
$z[8][4]['typeid']="17";
$z[8][4]['type']="son";
$z[9]=Array("list","\r\n                <li><a href=\"[field:arcurl/]\">\r\n            	<div class=\"pic\"><img src=\"[field:picname/]\" width=\"100%\" height=\"100%\"></div>\r\n                <div class=\"title\">[field:title/]（点击查看更多）</div>\r\n                <div class=\"info\">\r\n                	<h3>[field:title/]（点击查看更多）</h3>\r\n                    <p></p>\r\n                </div>\r\n                </a>\r\n                </li>\r\n            ",5180,5639);
$z[9][4]=array();

?>