<?php
$z[0]=Array("global","",141,167);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",208,235);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",274,304);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",2416,2443);
$z[3][4]=array();
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("channel","\n                <li class=\" button button--wayra button--border-thick button--text-upper button--size-s\"><a  href=\"[field:typelink/]\"><div class=\"bai\">[field:typename/]</div><div class=\"hong\">[field:typename/]</div></a>\n                </li>\n            ",2547,2859);
$z[4][4]=array();
$z[4][4]['row']="8";
$z[4][4]['type']="top";
$z[5]=Array("channel","\n                <li><a href=\"[field:typelink/]\" class=\"button button--moema button--text-thick button--text-upper button--size-s\">[field:typename/]</a></li>\n                ",5688,5934);
$z[5][4]=array();
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['typeid']="28";
$z[6]=Array("channel","\n                        <li class=\"p5\">\n                            <a href=\"[field:typelink/]\">\n                                <u class=\"cl\"></u>\n                                <u class=\"cr\"></u>\n                                <i></i>\n                                <strong>[field:typename/]</strong>\n                                <p><!-- {dede:field.seotitle /} --><br />彰显品牌形象</p>\n                            </a>\n                        </li>\n                    ",11217,11776);
$z[6][4]=array();
$z[6][4]['row']="10";
$z[6][4]['type']="son";
$z[6][4]['typeid']="28";
$z[7]=Array("arclist","\n                        <li>\n                            <div class=\"pic\"><img src=\"[field:picname/]\" width=\"100%\" height=\"100%\"></div>\n                            <div class=\"con\">\n                                <div class=\"title\">\n                                    <a href=\"[field:arcurl/]\"><h1>[field:title/]</h1></a>\n                                    <div class=\"date\">[field:pubdate function=\"GetDateTimeMK(@me)\" /]</div>\n                                    <div style=\"clear:both;\"></div>\n                                </div>\n                                <p>[field:description /]</p>\n                                <a href=\"http://xcp.huashifengxing.com/a/xinwenzhongxin/\" class=\"more button button--moema button--inverted button--text-thick button--size-s\">MORE</a>\n                            </div>\n                        </li>\n                        ",53584,54512);
$z[7][4]=array();
$z[7][4]['pagesize']="2";
$z[7][4]['typeid']="2";
$z[8]=Array("arclist","\n                                <li>\n                                    <div class=\"pic\"><img src=\"[field:litpic/]\" width=\"100%\" height=\"100%\"></div>\n                                    <div class=\"title5\">[field:title/]</div>\n                                    <div class=\"msakbj\"></div>\n                                </li>\n                                 ",55947,56359);
$z[8][4]=array();
$z[8][4]['row']="3";
$z[8][4]['typeid']="2";

?>