<?php
$z[0]=Array("global","",132,158);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",199,226);
$z[1][4]=array();
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",265,295);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",1668,1695);
$z[3][4]=array();
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("channel","\n                <li class=\" button button--wayra button--border-thick button--text-upper button--size-s\"><a  href=\"[field:typelink/]\"><div class=\"bai\">[field:typename/]</div><div class=\"hong\">[field:typename/]</div></a>\n                </li>\n            ",1799,2111);
$z[4][4]=array();
$z[4][4]['row']="8";
$z[4][4]['type']="top";
$z[5]=Array("channel","\n                <li><a href=\"[field:typelink/]\" class=\"button button--moema button--text-thick button--text-upper button--size-s\">[field:typename/]</a></li>\n                ",4847,5093);
$z[5][4]=array();
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['typeid']="28";
$z[6]=Array("channel","\n                        <li class=\"p5\">\n                            <a href=\"[field:typelink/]\">\n                                <u class=\"cl\"></u>\n                                <u class=\"cr\"></u>\n                                <i></i>\n                                <strong>[field:typename/]</strong>\n                                <p>{dede:field.content/}<br />彰显品牌形象</p>\n                            </a>\n                        </li>\n                    ",10429,10977);
$z[6][4]=array();
$z[6][4]['row']="10";
$z[6][4]['type']="son";
$z[6][4]['typeid']="28";
$z[7]=Array("channel","\n                <a href=\"[field:typelink/]\" class=\"more1 button button--rayen button--border-thin button--text-thick button--text-upper button--size-s\" data-text=\"查看更多\"><span>查看更多</span></a>\n                ",15588,15878);
$z[7][4]=array();
$z[7][4]['type']="top";
$z[7][4]['typeid']="28";

?>