<?php
$z[0]=Array("field","",64,83);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",84,110);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",153,180);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",220,271);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",2045,2072);
$z[4][4]=array();
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("channel","\r\n                <li class=\" button button--wayra button--border-thick button--text-upper button--size-s\"><a style=\"font-size:16px;\" href=\"[field:typelink/]\"><div class=\"bai\">[field:typename/]</div><div class=\"hong\">profile</div></a>\r\n                </li>\r\n            ",2158,2486);
$z[5][4]=array();
$z[5][4]['row']="8";
$z[5][4]['type']="top";
$z[6]=Array("include","",22452,22489);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>