<?php
$z[0]=Array("global","",176,204);
$z[0][4]=array();
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",272,291);
$z[1][4]=array();
$z[1][4]['name']="title";
$z[2]=Array("global","",292,318);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",359,388);
$z[3][4]=array();
$z[3][4]['name']="keywords";
$z[4]=Array("field","",428,486);
$z[4][4]=array();
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",1072,1111);
$z[5][4]=array();
$z[5][4]['filename']="header_m.htm";
$z[6]=Array("channel"," <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a> ",1194,1292);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[7]=Array("field","",1350,1379);
$z[7][4]=array();
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n      <li> <a href=\"view.php?aid=[field:id/]\">\r\n        <p>[field:title/]</p>\r\n        </a> </li>\r\n     ",1445,1589);
$z[8][4]=array();
$z[8][4]['pagesize']="8";
$z[9]=Array("pagelist","",1636,1702);
$z[9][4]=array();
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",1732,1771);
$z[10][4]=array();
$z[10][4]['filename']="footer_m.htm";

?>